/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AetheriusEquityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOfEncrypted"
      | "crossChainLiquidate"
      | "encryptedStorage"
      | "grantAuditorAccess"
      | "name"
      | "owner"
      | "registerAuditorPublicKey"
      | "registrar"
      | "symbol"
      | "transferEncrypted"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AuditorKeyRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "balanceOfEncrypted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "crossChainLiquidate",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantAuditorAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAuditorPublicKey",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registrar", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferEncrypted",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "balanceOfEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossChainLiquidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAuditorAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAuditorPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registrar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferEncrypted",
    data: BytesLike
  ): Result;
}

export namespace AuditorKeyRegisteredEvent {
  export type InputTuple = [auditor: AddressLike, publicKey: BytesLike];
  export type OutputTuple = [auditor: string, publicKey: string];
  export interface OutputObject {
    auditor: string;
    publicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AetheriusEquity extends BaseContract {
  connect(runner?: ContractRunner | null): AetheriusEquity;
  waitForDeployment(): Promise<this>;

  interface: AetheriusEquityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOfEncrypted: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  crossChainLiquidate: TypedContractMethod<
    [
      destinationChainID: BytesLike,
      targetAddress: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  encryptedStorage: TypedContractMethod<[], [string], "view">;

  grantAuditorAccess: TypedContractMethod<
    [auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAuditorPublicKey: TypedContractMethod<
    [auditor: AddressLike, publicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  registrar: TypedContractMethod<[], [string], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  transferEncrypted: TypedContractMethod<
    [encryptedAmount: BytesLike, zkProof: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOfEncrypted"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "crossChainLiquidate"
  ): TypedContractMethod<
    [
      destinationChainID: BytesLike,
      targetAddress: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptedStorage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantAuditorAccess"
  ): TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAuditorPublicKey"
  ): TypedContractMethod<
    [auditor: AddressLike, publicKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferEncrypted"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, zkProof: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "AuditorKeyRegistered"
  ): TypedContractEvent<
    AuditorKeyRegisteredEvent.InputTuple,
    AuditorKeyRegisteredEvent.OutputTuple,
    AuditorKeyRegisteredEvent.OutputObject
  >;

  filters: {
    "AuditorKeyRegistered(address,bytes)": TypedContractEvent<
      AuditorKeyRegisteredEvent.InputTuple,
      AuditorKeyRegisteredEvent.OutputTuple,
      AuditorKeyRegisteredEvent.OutputObject
    >;
    AuditorKeyRegistered: TypedContractEvent<
      AuditorKeyRegisteredEvent.InputTuple,
      AuditorKeyRegisteredEvent.OutputTuple,
      AuditorKeyRegisteredEvent.OutputObject
    >;
  };
}
