/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IEncryptedERC, IEncryptedERCInterface } from "../IEncryptedERC";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "encryptedAmount",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "zkProof",
        type: "bytes",
      },
    ],
    name: "encryptedTransfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getEncryptedBalance",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEncryptedERC__factory {
  static readonly abi = _abi;
  static createInterface(): IEncryptedERCInterface {
    return new Interface(_abi) as IEncryptedERCInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEncryptedERC {
    return new Contract(address, _abi, runner) as unknown as IEncryptedERC;
  }
}
