/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IRegistrar, IRegistrarInterface } from "../IRegistrar";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "auditor",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "publicKey",
        type: "bytes",
      },
    ],
    name: "registerAuditorKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRegistrar__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistrarInterface {
    return new Interface(_abi) as IRegistrarInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRegistrar {
    return new Contract(address, _abi, runner) as unknown as IRegistrar;
  }
}
